"""add harness fields agent_memories tools agent_tools agent_change_log

Revision ID: a77f4d6b0784
Revises: fb021470557f
Create Date: 2026-05-08 17:29:09.942528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77f4d6b0784'
down_revision: Union[str, Sequence[str], None] = 'fb021470557f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('params_schema_json', sa.Text(), nullable=False),
    sa.Column('returns_schema_json', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_platform'), ['platform'], unique=False)

    op.create_table('agent_change_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_change_log_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_change_log_created_at'), ['created_at'], unique=False)

    op.create_table('agent_memories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_memories_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_memories_kind'), ['kind'], unique=False)

    op.create_table('agent_tools',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        # 老 row 无值 · server_default='normal' 让 NOT NULL 升级安全
        batch_op.add_column(sa.Column('role', sa.String(length=16), nullable=False, server_default='normal'))
        batch_op.add_column(sa.Column('rules_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agents_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_role'))
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('rules_json')
        batch_op.drop_column('role')

    op.drop_table('agent_tools')
    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_memories_kind'))
        batch_op.drop_index(batch_op.f('ix_agent_memories_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_memories_agent_id'))

    op.drop_table('agent_memories')
    with op.batch_alter_table('agent_change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_change_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_change_log_agent_id'))

    op.drop_table('agent_change_log')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_platform'))

    op.drop_table('tools')
    # ### end Alembic commands ###
