"""add hermes akong_skills akong_tools agent_skills agent_akong_tools

Revision ID: f321d38cbd2a
Revises: fb2c73176ea9
Create Date: 2026-05-09 02:34:14.623112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f321d38cbd2a'
down_revision: Union[str, Sequence[str], None] = 'fb2c73176ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akong_skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sop_markdown', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('static_ref', sa.String(length=128), nullable=True),
    sa.Column('code_python', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('akong_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_akong_skills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_akong_skills_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_akong_skills_source'), ['source'], unique=False)

    op.create_table('akong_tools',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('static_ref', sa.String(length=128), nullable=True),
    sa.Column('code_python', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('akong_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_akong_tools_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_akong_tools_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_akong_tools_source'), ['source'], unique=False)

    op.create_table('agent_akong_tools',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['akong_tools.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    with op.batch_alter_table('agent_akong_tools', schema=None) as batch_op:
        batch_op.create_index('ix_agent_akong_tools_agent_tool', ['agent_id', 'tool_id'], unique=False)

    op.create_table('agent_skills',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['akong_skills.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    with op.batch_alter_table('agent_skills', schema=None) as batch_op:
        batch_op.create_index('ix_agent_skills_agent_skill', ['agent_id', 'skill_id'], unique=False)

    op.create_table('hermes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('soul', sa.Text(), nullable=False),
    sa.Column('playbook', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('static_ref', sa.String(length=64), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hermes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hermes_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hermes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hermes_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hermes_static_ref'), ['static_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hermes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hermes_static_ref'))
        batch_op.drop_index(batch_op.f('ix_hermes_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_hermes_created_at'))
        batch_op.drop_index(batch_op.f('ix_hermes_agent_id'))

    op.drop_table('hermes')
    with op.batch_alter_table('agent_skills', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_skills_agent_skill')

    op.drop_table('agent_skills')
    with op.batch_alter_table('agent_akong_tools', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_akong_tools_agent_tool')

    op.drop_table('agent_akong_tools')
    with op.batch_alter_table('akong_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_akong_tools_source'))
        batch_op.drop_index(batch_op.f('ix_akong_tools_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_akong_tools_created_at'))

    op.drop_table('akong_tools')
    with op.batch_alter_table('akong_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_akong_skills_source'))
        batch_op.drop_index(batch_op.f('ix_akong_skills_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_akong_skills_created_at'))

    op.drop_table('akong_skills')
    # ### end Alembic commands ###
